# Generated by Django 5.0.6 on 2024-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=20)),
                ('free_shipping', models.CharField(max_length=20)),
                ('student_discount_amount', models.CharField(max_length=20)),
                ('discount_amount', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
