# Generated by Django 5.0.6 on 2024-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_showoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='showoffer',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
