# Generated by Django 5.0.6 on 2024-07-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_2',
            field=models.ImageField(default='', upload_to='product_thumbnails'),
        ),
    ]
