# Generated by Django 5.0.6 on 2024-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_thumbnail_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail_2',
            field=models.ImageField(upload_to='product_thumbnails'),
        ),
    ]
